/*
 *  Copyright (c) Texas Instruments Incorporated 2026
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/*!
 * \file  enet_ioctl_register_multi_priv.h
 *
 * \brief IOCTL handler registration when CPSW and ICSSG are built together.
 *
 * Handlers of an IOCTL command are registered lazily by the ENET_IOCTL() macro,
 * which calls Enet_ioctl_register_<cmd>(). Each peripheral defines that
 * function for the IOCTLs it implements, so a library built with both
 * ENET_ENABLE_PER_CPSW and ENET_ENABLE_PER_ICSSG would get two definitions of
 * it for the IOCTLs that both peripherals implement.
 *
 * In that case the peripheral files define Cpsw_ioctl_register_<cmd>() and
 * Icssg_ioctl_register_<cmd>() instead, and enet_ioctl_register_multi.c
 * defines Enet_ioctl_register_<cmd>() to call the one of the peripheral that
 * the Enet handle belongs to.
 *
 * A peripheral IOCTL registration file selects its prefix before including
 * this header:
 *   #define ENET_IOCTL_REGISTER_PER_CPSW  or  #define ENET_IOCTL_REGISTER_PER_ICSSG
 */

#ifndef ENET_IOCTL_REGISTER_MULTI_PRIV_H_
#define ENET_IOCTL_REGISTER_MULTI_PRIV_H_

/* ========================================================================== */
/*                           Macros & Typedefs                                */
/* ========================================================================== */

#if defined(ENET_ENABLE_PER_CPSW) && defined(ENET_ENABLE_PER_ICSSG)
/*! \brief CPSW and ICSSG are built into the same library */
#define ENET_IOCTL_REGISTER_MULTI_PER

/*! \brief IOCTLs implemented by both CPSW and ICSSG */
#define ENET_IOCTL_REGISTER_MULTI_PER_CMDS(X) \
    X(ENET_PER_IOCTL_OPEN_PORT_LINK) \
    X(ENET_PER_IOCTL_CLOSE_PORT_LINK) \
    X(ENET_PER_IOCTL_IS_PORT_LINK_UP) \
    X(ENET_PER_IOCTL_GET_PORT_LINK_CFG) \
    X(ENET_PER_IOCTL_ATTACH_CORE) \
    X(ENET_PER_IOCTL_DETACH_CORE) \
    X(ENET_PER_IOCTL_HANDLE_EXTPHY_LINKUP_EVENT) \
    X(ENET_PER_IOCTL_HANDLE_EXTPHY_LINKDOWN_EVENT) \
    X(ENET_IOCTL_REGISTER_RX_DEFAULT_FLOW) \
    X(ENET_IOCTL_UNREGISTER_RX_DEFAULT_FLOW) \
    X(ENET_MACPORT_IOCTL_SET_PRI_REGEN_MAP) \
    X(ENET_MACPORT_IOCTL_GET_PRI_REGEN_MAP) \
    X(ENET_MACPORT_IOCTL_SET_EGRESS_QOS_PRI_MAP) \
    X(ENET_MACPORT_IOCTL_GET_EGRESS_QOS_PRI_MAP) \
    X(ENET_MACPORT_IOCTL_SET_INGRESS_DSCP_PRI_MAP) \
    X(ENET_MACPORT_IOCTL_GET_INGRESS_DSCP_PRI_MAP) \
    X(ENET_STATS_IOCTL_GET_HOSTPORT_STATS) \
    X(ENET_STATS_IOCTL_GET_MACPORT_STATS) \
    X(ENET_STATS_IOCTL_RESET_HOSTPORT_STATS) \
    X(ENET_STATS_IOCTL_RESET_MACPORT_STATS) \
    X(ENET_TIMESYNC_IOCTL_GET_CURRENT_TIMESTAMP) \
    X(ENET_TIMESYNC_IOCTL_SET_TIMESTAMP) \
    X(ENET_TIMESYNC_IOCTL_ADJUST_TIMESTAMP) \
    X(ENET_TIMESYNC_IOCTL_GET_ETH_TX_TIMESTAMP)

/*! \brief Preemption IOCTLs implemented by ICSSG, and by CPSW when CPSW_IET_INCL is on */
#define ENET_IOCTL_REGISTER_MULTI_PER_IET_CMDS(X) \
    X(ENET_MACPORT_IOCTL_ENABLE_PREEMPTION) \
    X(ENET_MACPORT_IOCTL_DISABLE_PREEMPTION) \
    X(ENET_MACPORT_IOCTL_GET_PREEMPTION_ENABLE_STATUS) \
    X(ENET_MACPORT_IOCTL_GET_PREEMPTION_ACTIVE_STATUS) \
    X(ENET_MACPORT_IOCTL_ENABLE_PREEMPT_VERIFICATION) \
    X(ENET_MACPORT_IOCTL_DISABLE_PREEMPT_VERIFICATION) \
    X(ENET_MACPORT_IOCTL_GET_PREEMPT_VERIFY_STATUS) \
    X(ENET_MACPORT_IOCTL_GET_PREEMPT_MIN_FRAG_SIZE) \
    X(ENET_MACPORT_IOCTL_SET_PREEMPT_MIN_FRAG_SIZE) \
    X(ENET_MACPORT_IOCTL_SET_PREEMPT_QUEUE) \
    X(ENET_MACPORT_IOCTL_GET_QUEUE_PREEMPT_STATUS)

/*! \brief TAS IOCTLs implemented by ICSSG, and by CPSW when CPSW_EST is on */
#define ENET_IOCTL_REGISTER_MULTI_PER_EST_CMDS(X) \
    X(ENET_TAS_IOCTL_SET_ADMIN_LIST) \
    X(ENET_TAS_IOCTL_GET_ADMIN_LIST) \
    X(ENET_TAS_IOCTL_GET_OPER_LIST) \
    X(ENET_TAS_IOCTL_SET_STATE) \
    X(ENET_TAS_IOCTL_GET_STATE) \
    X(ENET_TAS_IOCTL_GET_OPER_LIST_STATUS) \
    X(ENET_TAS_IOCTL_CONFIG_CHANGE_STATUS_PARAMS)

#if defined(ENET_IOCTL_REGISTER_PER_CPSW)
#define ENET_IOCTL_REGISTER_PER_FXN(cmd)    Cpsw_ioctl_register_##cmd
#elif defined(ENET_IOCTL_REGISTER_PER_ICSSG)
#define ENET_IOCTL_REGISTER_PER_FXN(cmd)    Icssg_ioctl_register_##cmd
#endif

#if defined(ENET_IOCTL_REGISTER_PER_FXN)
/* Rename the registration functions generated by the peripheral file */
#define Enet_ioctl_register_ENET_PER_IOCTL_OPEN_PORT_LINK                    ENET_IOCTL_REGISTER_PER_FXN(ENET_PER_IOCTL_OPEN_PORT_LINK)
#define Enet_ioctl_register_ENET_PER_IOCTL_CLOSE_PORT_LINK                   ENET_IOCTL_REGISTER_PER_FXN(ENET_PER_IOCTL_CLOSE_PORT_LINK)
#define Enet_ioctl_register_ENET_PER_IOCTL_IS_PORT_LINK_UP                   ENET_IOCTL_REGISTER_PER_FXN(ENET_PER_IOCTL_IS_PORT_LINK_UP)
#define Enet_ioctl_register_ENET_PER_IOCTL_GET_PORT_LINK_CFG                 ENET_IOCTL_REGISTER_PER_FXN(ENET_PER_IOCTL_GET_PORT_LINK_CFG)
#define Enet_ioctl_register_ENET_PER_IOCTL_ATTACH_CORE                       ENET_IOCTL_REGISTER_PER_FXN(ENET_PER_IOCTL_ATTACH_CORE)
#define Enet_ioctl_register_ENET_PER_IOCTL_DETACH_CORE                       ENET_IOCTL_REGISTER_PER_FXN(ENET_PER_IOCTL_DETACH_CORE)
#define Enet_ioctl_register_ENET_PER_IOCTL_HANDLE_EXTPHY_LINKUP_EVENT        ENET_IOCTL_REGISTER_PER_FXN(ENET_PER_IOCTL_HANDLE_EXTPHY_LINKUP_EVENT)
#define Enet_ioctl_register_ENET_PER_IOCTL_HANDLE_EXTPHY_LINKDOWN_EVENT      ENET_IOCTL_REGISTER_PER_FXN(ENET_PER_IOCTL_HANDLE_EXTPHY_LINKDOWN_EVENT)
#define Enet_ioctl_register_ENET_IOCTL_REGISTER_RX_DEFAULT_FLOW              ENET_IOCTL_REGISTER_PER_FXN(ENET_IOCTL_REGISTER_RX_DEFAULT_FLOW)
#define Enet_ioctl_register_ENET_IOCTL_UNREGISTER_RX_DEFAULT_FLOW            ENET_IOCTL_REGISTER_PER_FXN(ENET_IOCTL_UNREGISTER_RX_DEFAULT_FLOW)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_SET_PRI_REGEN_MAP             ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_SET_PRI_REGEN_MAP)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_GET_PRI_REGEN_MAP             ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_GET_PRI_REGEN_MAP)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_SET_EGRESS_QOS_PRI_MAP        ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_SET_EGRESS_QOS_PRI_MAP)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_GET_EGRESS_QOS_PRI_MAP        ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_GET_EGRESS_QOS_PRI_MAP)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_SET_INGRESS_DSCP_PRI_MAP      ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_SET_INGRESS_DSCP_PRI_MAP)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_GET_INGRESS_DSCP_PRI_MAP      ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_GET_INGRESS_DSCP_PRI_MAP)
#define Enet_ioctl_register_ENET_STATS_IOCTL_GET_HOSTPORT_STATS              ENET_IOCTL_REGISTER_PER_FXN(ENET_STATS_IOCTL_GET_HOSTPORT_STATS)
#define Enet_ioctl_register_ENET_STATS_IOCTL_GET_MACPORT_STATS               ENET_IOCTL_REGISTER_PER_FXN(ENET_STATS_IOCTL_GET_MACPORT_STATS)
#define Enet_ioctl_register_ENET_STATS_IOCTL_RESET_HOSTPORT_STATS            ENET_IOCTL_REGISTER_PER_FXN(ENET_STATS_IOCTL_RESET_HOSTPORT_STATS)
#define Enet_ioctl_register_ENET_STATS_IOCTL_RESET_MACPORT_STATS             ENET_IOCTL_REGISTER_PER_FXN(ENET_STATS_IOCTL_RESET_MACPORT_STATS)
#define Enet_ioctl_register_ENET_TIMESYNC_IOCTL_GET_CURRENT_TIMESTAMP        ENET_IOCTL_REGISTER_PER_FXN(ENET_TIMESYNC_IOCTL_GET_CURRENT_TIMESTAMP)
#define Enet_ioctl_register_ENET_TIMESYNC_IOCTL_SET_TIMESTAMP                ENET_IOCTL_REGISTER_PER_FXN(ENET_TIMESYNC_IOCTL_SET_TIMESTAMP)
#define Enet_ioctl_register_ENET_TIMESYNC_IOCTL_ADJUST_TIMESTAMP             ENET_IOCTL_REGISTER_PER_FXN(ENET_TIMESYNC_IOCTL_ADJUST_TIMESTAMP)
#define Enet_ioctl_register_ENET_TIMESYNC_IOCTL_GET_ETH_TX_TIMESTAMP         ENET_IOCTL_REGISTER_PER_FXN(ENET_TIMESYNC_IOCTL_GET_ETH_TX_TIMESTAMP)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_ENABLE_PREEMPTION             ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_ENABLE_PREEMPTION)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_DISABLE_PREEMPTION            ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_DISABLE_PREEMPTION)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_GET_PREEMPTION_ENABLE_STATUS  ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_GET_PREEMPTION_ENABLE_STATUS)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_GET_PREEMPTION_ACTIVE_STATUS  ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_GET_PREEMPTION_ACTIVE_STATUS)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_ENABLE_PREEMPT_VERIFICATION   ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_ENABLE_PREEMPT_VERIFICATION)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_DISABLE_PREEMPT_VERIFICATION  ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_DISABLE_PREEMPT_VERIFICATION)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_GET_PREEMPT_VERIFY_STATUS     ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_GET_PREEMPT_VERIFY_STATUS)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_GET_PREEMPT_MIN_FRAG_SIZE     ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_GET_PREEMPT_MIN_FRAG_SIZE)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_SET_PREEMPT_MIN_FRAG_SIZE     ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_SET_PREEMPT_MIN_FRAG_SIZE)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_SET_PREEMPT_QUEUE             ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_SET_PREEMPT_QUEUE)
#define Enet_ioctl_register_ENET_MACPORT_IOCTL_GET_QUEUE_PREEMPT_STATUS      ENET_IOCTL_REGISTER_PER_FXN(ENET_MACPORT_IOCTL_GET_QUEUE_PREEMPT_STATUS)
#define Enet_ioctl_register_ENET_TAS_IOCTL_SET_ADMIN_LIST                    ENET_IOCTL_REGISTER_PER_FXN(ENET_TAS_IOCTL_SET_ADMIN_LIST)
#define Enet_ioctl_register_ENET_TAS_IOCTL_GET_ADMIN_LIST                    ENET_IOCTL_REGISTER_PER_FXN(ENET_TAS_IOCTL_GET_ADMIN_LIST)
#define Enet_ioctl_register_ENET_TAS_IOCTL_GET_OPER_LIST                     ENET_IOCTL_REGISTER_PER_FXN(ENET_TAS_IOCTL_GET_OPER_LIST)
#define Enet_ioctl_register_ENET_TAS_IOCTL_SET_STATE                         ENET_IOCTL_REGISTER_PER_FXN(ENET_TAS_IOCTL_SET_STATE)
#define Enet_ioctl_register_ENET_TAS_IOCTL_GET_STATE                         ENET_IOCTL_REGISTER_PER_FXN(ENET_TAS_IOCTL_GET_STATE)
#define Enet_ioctl_register_ENET_TAS_IOCTL_GET_OPER_LIST_STATUS              ENET_IOCTL_REGISTER_PER_FXN(ENET_TAS_IOCTL_GET_OPER_LIST_STATUS)
#define Enet_ioctl_register_ENET_TAS_IOCTL_CONFIG_CHANGE_STATUS_PARAMS       ENET_IOCTL_REGISTER_PER_FXN(ENET_TAS_IOCTL_CONFIG_CHANGE_STATUS_PARAMS)
#endif /* ENET_IOCTL_REGISTER_PER_FXN */

#endif /* ENET_ENABLE_PER_CPSW && ENET_ENABLE_PER_ICSSG */

#endif /* ENET_IOCTL_REGISTER_MULTI_PRIV_H_ */
